[package]
name = "vector-text"
description = "Text shaping and glyph outline extraction"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
vector-geom = { path = "../vector-geom" }
rustybuzz = { workspace = true }
ttf-parser = { workspace = true }
fontdb = { workspace = true }
log = { workspace = true }
